# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
changelog:
  exclude:
    labels:
      - category:housekeeping
      - Build
      - CI
      - Maintenance
  categories:
    - title: 🐛 Bug Fixes  # legate-lint: no-ascii-only
      labels:
        - category:bug-fix
        - Bug
    - title: 🚀 New Features  # legate-lint: no-ascii-only
      labels:
        - category:new-feature
        - Feature
    - title: 🛠️ Improvements  # legate-lint: no-ascii-only
      labels:
        - category:improvement
    - title: 📖 Documentation  # legate-lint: no-ascii-only
      labels:
        - category:documentation
        - Docs
