---
changelog:
  exclude:
    labels:
      - category:housekeeping
      - Build
      - CI
      - Maintenance
  categories:
    - title: 🐛 Bug Fixes  # legate-lint: no-ascii-only
      labels:
        - category:bug-fix
        - Bug
    - title: 🚀 New Features  # legate-lint: no-ascii-only
      labels:
        - category:new-feature
        - Feature
    - title: 🛠️ Improvements  # legate-lint: no-ascii-only
      labels:
        - category:improvement
    - title: 📖 Documentation  # legate-lint: no-ascii-only
      labels:
        - category:documentation
        - Docs
