---
{% set name = "realm-gex-wrapper" %}
{% set major_version = (version|string).split(".")[0] %}
{% set minor_version = (version|string).split(".")[1] %}
{% set patch_version = (version|string).split(".")[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://gitlab.com/StanfordLegion/legion.git

build:
  include_recipe: false
  number: 13
  skip: true  # [not linux]
  noarch: generic
  script_env:
    - PKG_NAME={{ name }}

extra:
  recipe-maintainers:
    - m3vaz
    - marcinz
