# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
{% set name = "realm-gex-wrapper" %}

{% set legate_version = environ.get('LEGATE_VERSION') %}

{% set legion_sha = environ.get('LEGION_GIT_REV', 'master') %}
{% set git_url = environ.get('LEGION_GIT_URL', 'https://gitlab.com/StanfordLegion/legion.git') %}

package:
  name: {{ name|lower }}
  version: {{ legate_version }}

source:
  git_url: {{ git_url }}
  git_rev: {{ legion_sha }}

build:
  include_recipe: false
  number: 22
  skip: true  # [not linux]
  noarch: generic
  script_env:
    - PKG_NAME={{ name }}

requirements:
  run:
    - legate ={{ legate_version }}

extra:
  recipe-maintainers:
    - m3vaz
    - marcinz
