# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import os
import sys
from contextlib import contextmanager, suppress
from functools import cache
from pathlib import Path
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from collections.abc import Generator


@contextmanager
def _push_legate_dir_to_sys_path() -> Generator[None, None, None]:
    root_dir = str(Path(__file__).parents[4].resolve(strict=True))
    sys.path.insert(0, root_dir)

    try:
        yield
    finally:
        with suppress(ValueError):
            sys.path.remove(root_dir)


def _get_legate_dir() -> Path:
    if not (legate_dir := os.environ.get("LEGATE_DIR", "").strip()):
        with _push_legate_dir_to_sys_path():
            # Technically _push_legate_dir_to_sys_path() already gets us 99% of
            # the way to LEGATE_DIR, but let's use the get_legate_dir utility
            # anyway
            from scripts.get_legate_dir import get_legate_dir  # noqa: PLC0415

        legate_dir = get_legate_dir()

    legate_path = Path(legate_dir).resolve(strict=True)
    os.environ["LEGATE_DIR"] = str(legate_path)
    return legate_path


def _get_legate_arch() -> str:
    if legate_arch := os.environ.get("LEGATE_ARCH", "").strip():
        return legate_arch

    try:
        with _push_legate_dir_to_sys_path():
            from scripts.get_legate_arch import (  # type: ignore[import-not-found,unused-ignore]  # noqa: PLC0415
                get_legate_arch,
            )
    except ModuleNotFoundError:
        from ._io import warning_print  # noqa: PLC0415

        # User has not run configure, so come up with a suitable name.
        def get_legate_arch() -> str:
            return "arch-autogenerated-skbuild-core"

        warning_print(
            "Running pip install without first configuring Legate. "
            f"Using an autogenerated legate arch name {get_legate_arch()}"
        )

    legate_arch = get_legate_arch()
    os.environ["LEGATE_ARCH"] = legate_arch
    return legate_arch


class LegateConfig:
    def __init__(self) -> None:
        self.LEGATE_DIR: Final = _get_legate_dir()
        self.LEGATE_ARCH: Final = _get_legate_arch()

    @property
    def LEGATE_ARCH_DIR(self) -> Path:
        return self.LEGATE_DIR / self.LEGATE_ARCH

    @property
    def LEGATE_CMAKE_DIR(self) -> Path:
        return self.LEGATE_ARCH_DIR / "cmake_build"

    @property
    def SKBUILD_BUILD_DIR(self) -> Path:
        return self.LEGATE_ARCH_DIR / "skbuild_core"


@cache
def get_legate_config() -> LegateConfig:
    return LegateConfig()
