# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

class DomainPoint:
    def __init__(self) -> None: ...
    @property
    def dim(self) -> int: ...
    def __getitem__(self, idx: int) -> int: ...
    def __setitem__(self, idx: int, coord: int) -> None: ...

class Domain:
    def __init__(self) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def lo(self) -> DomainPoint: ...
    @property
    def hi(self) -> DomainPoint: ...
