# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
{% set name = "legate" %}

{% set legate_version = environ.get('LEGATE_VERSION') %}
{% set git_describe_hash = environ.get('GIT_DESCRIBE_HASH', '0') %}

package:
  name: {{ name|lower }}
  version: {{ legate_version }}

build:
  number: 0
  skip: true  # [not linux]
  string: {{ git_describe_hash }}

requirements:
  build: []
  run: []

extra:
  recipe-maintainers:
    - m3vaz
