# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
{% set name = "legate" %}

{% set default_env_var = '' %}
{% set legate_version = '' %}
{% if LEGATE_GIT_DESCRIBE_TAG is defined %}
    {% if 'dev' in environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var) %}
        {% set legate_version = (environ.get('LEGATE_GIT_DESCRIBE_TAG') ~ environ.get('LEGATE_GIT_DESCRIBE_NUMBER', default_env_var)).lstrip('v') %}
    {% else %}
        {% set legate_version = environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var).lstrip('v') %}
    {% endif %}
{% else %}
    {% set legate_version = '25.08.00' %}
{% endif %}

{% set major_version = (legate_version|string).split(".")[0] %}
{% set minor_version = (legate_version|string).split(".")[1] %}
{% set patch_version = (legate_version|string).split(".")[2] %}

{% set git_describe_hash = environ.get('GIT_DESCRIBE_HASH', '0') %}

package:
  name: {{ name|lower }}
  version: {{ legate_version }}

build:
  number: 0
  skip: true  # [not linux]
  string: {{ git_describe_hash }}

requirements:
  build: []
  run: []

extra:
  recipe-maintainers:
    - m3vaz
