#!/usr/bin/env bash

build_legate_cpp() {
    set -euo pipefail;

    begin_group "Configure Legate.Core"
    sccache --stop-server >/dev/null 2>&1 || true;

    if test -n "${CONDA_PREFIX:-}"; then
        export OPENSSL_DIR="${CONDA_PREFIX}";
    fi

    cd "${LEGATE_CORE_DIR}";

    local extra_configure_args=()
    # packages
    if [[ "${USE_CUDA}" == "ON" ]]; then
      extra_configure_args+=(--with-cuda)
      extra_configure_args+=(--cuda-arch=all-major)
    fi
    # if [[ "${USE_HDF5}" == "ON" ]]; then
    #   extra_configure_args+=(--with-hdf5)
    # fi
    if [[ "${UCX_ENABLED}" == "ON" ]]; then
      # TODO(marcinz): Broken! see
      # https://github.com/nv-legate/legate.core.internal/pull/470
      # extra_configure_args+=(--with-ucx)
      true
    fi
    if [[ "${USE_OPENMP}" == "ON" ]]; then
      extra_configure_args+=(--with-openmp)
    fi
    # if [[ "${USE_LLVM}" == "ON" ]]; then
    #   extra_configure_args+=(--with-llvm)
    # fi

    cat ./config/examples/"${LEGATE_CORE_ARCH}".py

    ./config/examples/"${LEGATE_CORE_ARCH}".py \
                     --build-march "${BUILD_MARCH}" \
                     "${extra_configure_args[@]}"

    sccache --show-stats;

    cp "${LEGATE_CORE_DIR}/${LEGATE_CORE_ARCH}"/configure.log "${ARTIFACTS_DIR}/${LEGATE_CORE_ARCH}"
    cp "${LEGATE_CORE_DIR}/${LEGATE_CORE_ARCH}/reconfigure-${LEGATE_CORE_ARCH}.py" "${ARTIFACTS_DIR}/${LEGATE_CORE_ARCH}"
    end_group
    begin_group "Build Legate.Core C++ Files"

    make package VERBOSE=1 | tee make.log

    cp make.log "${ARTIFACTS_DIR}/${LEGATE_CORE_ARCH}"

    sccache --show-stats;

    mkdir -p /tmp/out;
    cp "${LEGATE_CORE_DIR}"/"${LEGATE_CORE_ARCH}"/cmake_build/*-$(uname).sh /tmp/out/
    end_group
}

(build_legate_cpp "$@");
