#!/usr/bin/env bash

build_legate_wheel() {
    set -euo pipefail;

    local tmp_dir="/tmp/out"
    mkdir -p "${tmp_dir}";

    local pip_args=(-vv);
    pip_args+=(--wheel-dir "${tmp_dir}");

    if type conda 2>&1 >/dev/null; then
        pip_args+=(--no-deps);
        pip_args+=(--no-build-isolation);
    fi

    local ninja_args=();
    ninja_args+=("-v");
    ninja_args+=("-j${JOBS:-$(nproc --ignore=1)}");

    # Build + package legate.core Python wheel
    set +e
    time SKBUILD_BUILD_OPTIONS="${ninja_args[@]}" \
         pip wheel "${pip_args[@]}" ${LEGATE_CORE_DIR};
    ret=$?

    cp "${LEGATE_CORE_DIR}/${LEGATE_CORE_ARCH}"/_skbuild/*/*.log "${ARTIFACTS_DIR}/${LEGATE_CORE_ARCH}"
    set -e
    if [[ "${ret}" != "0" ]]; then
      set +e
      for log_file in "${LEGATE_CORE_DIR}/${LEGATE_CORE_ARCH}"/_skbuild/*/*.log; do
        echo "= ${log_file} =========================================================================================="
        cat "${log_file}"
        echo "= ${log_file} =========================================================================================="
      done
      set -e
      return ${ret}
    fi
}

(build_legate_wheel "$@");
