#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")/tools/legate-conda-utils"

make_conda_env() {
    case "$1" in
        ci) make_release_env;;
        release) make_release_env;;
        docs) get_yaml_and_make_conda_env;;
        *) return 1;;
    esac

    return 0;
}

(make_conda_env "$@");
