#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

export RAPIDS_SCRIPT_NAME="make-conda-env"

. "$(dirname "$0")/tools/legate-conda-utils"

make_conda_env() {
    case "$1" in
        ci) make_release_env;;
        nightly) make_release_env;;
        profiler) make_release_env ;;
        docs) get_yaml_and_make_conda_env;;
        *) return 1;;
    esac

    return 0;
}

(make_conda_env "$@");
