#!/usr/bin/env bash

# Shamelessly stolen from https://github.com/rapidsai/gha-tools/blob/main/tools/rapids-echo-stderr
# Echo to stderr helper function
STR=""
if [[ -n "${LEGATE_SCRIPT_NAME}" ]]; then
  STR+="[${LEGATE_SCRIPT_NAME}] "
fi
STR+="$*"

echo "${STR}" >&2
