# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
{% set name = "legate-mpi-wrapper" %}

{% set legate_version = environ.get('LEGATE_VERSION') %}

package:
  name: {{ name|lower }}
  version: {{ legate_version }}

source:
  git_url: ../../

build:
  include_recipe: false
  number: 19
  skip: true  # [not linux]
  noarch: generic
  script_env:
    - PKG_NAME={{ name }}

requirements:
  run:
    - legate ={{ legate_version }}

extra:
  recipe-maintainers:
    - m3vaz
    - marcinz
