---
{% set name = "legate-mpi-wrapper" %}
{% set major_version = (version|string).split(".")[0] %}
{% set minor_version = (version|string).split(".")[1] %}
{% set patch_version = (version|string).split(".")[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../../

build:
  include_recipe: false
  number: 19
  skip: true  # [not linux]
  noarch: generic
  script_env:
    - PKG_NAME={{ name }}

extra:
  recipe-maintainers:
    - m3vaz
    - marcinz
