# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from ...utilities.unconstructable import Unconstructable

class Config(Unconstructable):
    @property
    def auto_config(self) -> bool: ...
    @property
    def show_progress_requested(self) -> bool: ...
    @property
    def use_empty_task(self) -> bool: ...
    @property
    def warmup_nccl(self) -> bool: ...
    @property
    def enable_inline_task_launch(self) -> bool: ...
    @property
    def single_controller_execution(self) -> bool: ...
    @property
    def max_exception_size(self) -> int: ...
    @property
    def min_cpu_chunk(self) -> int: ...
    @property
    def min_gpu_chunk(self) -> int: ...
    @property
    def min_omp_chunk(self) -> int: ...
    @property
    def window_size(self) -> int: ...
    @property
    def field_reuse_frac(self) -> int: ...
    @property
    def field_reuse_freq(self) -> int: ...
    @property
    def consensus(self) -> bool: ...
    @property
    def disable_mpi(self) -> bool: ...
    @property
    def io_use_vfd_gds(self) -> bool: ...
    @property
    def num_omp_threads(self) -> int: ...
    @property
    def profile(self) -> bool: ...
    @property
    def profile_name(self) -> str: ...
    @property
    def provenance(self) -> bool: ...
    @property
    def experimental_copy_path(self) -> bool: ...
