---
{% set name = "legate-profiler" %}

{% set default_env_var = '' %}
{% set legate_version = '' %}
{% if LEGATE_GIT_DESCRIBE_TAG is defined %}
    {% if 'dev' in environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var) %}
        {% set legate_version = (environ.get('LEGATE_GIT_DESCRIBE_TAG') ~ environ.get('LEGATE_GIT_DESCRIBE_NUMBER', default_env_var)).lstrip('v') %}
    {% else %}
        {% set legate_version = environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var).lstrip('v') %}
    {% endif %}
{% else %}
    {% set legate_version = '25.03.02' %}
{% endif %}

{% set major_version = (legate_version|string).split(".")[0] %}
{% set minor_version = (legate_version|string).split(".")[1] %}
{% set patch_version = (legate_version|string).split(".")[2] %}

{% set git_rev = environ.get('LEGION_GIT_REV', 'master') %}
{% set git_url = environ.get('LEGION_GIT_URL', 'https://gitlab.com/StanfordLegion/legion.git') %}
{% set git_shallow = environ.get('LEGION_GIT_SHALLOW', true) %}
{% set git_describe_hash = environ.get('LEGATE_GIT_DESCRIBE_HASH', '0') %}

package:
  name: {{ name|lower }}
  version: {{ legate_version }}

source:
  git_url: {{ git_url }}
  git_rev: {{ git_rev }}
  git_shallow: {{ git_shallow }}

build:
  include_recipe: false
  number: 0
  skip: true  # [not linux]
  string: {{ git_describe_hash }}

requirements:
  build:
    - rust >={{ rust_min_version }}
    - {{ compiler('c') }}
    - libclang
    - clang

  host:
    - openssl

  run:
    - legate ={{ legate_version }}

extra:
  recipe-maintainers:
    - m3vaz
