# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
{% set name = "legate-profiler" %}

{% if gpu_enabled == "true" %}
  {% set gpu_enabled_bool = true %}
  {% set cpu_gpu_tag='' %}
{% elif gpu_enabled == "false" %}
  {% set gpu_enabled_bool = false %}
  {% set cpu_gpu_tag='_cpu' %}
{% else %}
  {% set gpu_enabled_bool = false %}
{% endif %}

{% if build_number is not defined %}
    {% set build_number = environ.get('LEGATE_GIT_DESCRIBE_NUMBER', '0') %}
{% endif %}

{% set legate_version = environ.get('LEGATE_VERSION') %}
{% set default_env_var = legate_version or '' %}

{% if 'dev' in environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var) %}
    {% set legate_prof_version = (environ.get('LEGATE_GIT_DESCRIBE_TAG') ~ environ.get('LEGATE_GIT_DESCRIBE_NUMBER', default_env_var)).lstrip('v') %}
{% else %}
    {% set legate_prof_version = environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var).lstrip('v') %}
{% endif %}

{% set git_rev = environ.get('LEGION_GIT_REV', 'master') %}
{% set git_url = environ.get('LEGION_GIT_URL', 'https://gitlab.com/StanfordLegion/legion.git') %}
{% set git_shallow = environ.get('LEGION_GIT_SHALLOW', true) %}
{% set git_describe_hash = environ.get('LEGATE_GIT_DESCRIBE_HASH', '0') %}

{% set cuda_version=environ.get('LEGATE_CUDA_VERSION') %}
{% if not cuda_version %}
invalid_yaml_missing_cuda_version: LEGATE_CUDA_VERSION must be set
{% endif %}
{% set cuda_major=cuda_version.split('.')[0]|int %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: {{ name|lower }}
  version: {{ legate_prof_version }}

source:
  git_url: {{ git_url }}
  git_rev: {{ git_rev }}
  git_shallow: {{ git_shallow }}

build:
  include_recipe: false
  number: {{ build_number }}
  skip: true  # [not linux]
  string: {{ git_describe_hash }}_{{ PKG_BUILDNUM }}
  script_env:
    - LIBCLANG_PATH=$BUILD_PREFIX/lib
  {% if gpu_enabled_bool %}
    - BUILD_WITH_CUDA=1
  {% else %}
    - BUILD_WITH_CUDA=0
  {% endif %}

requirements:
  build:
    - cmake
    - make
    - rust >={{ rust_min_version }}
    - {{ compiler('c') }}
    - libclang
    - clang
    - pkgconfig
    {% if gpu_enabled_bool %}
    - cuda-nvcc
    - cuda-cudart-dev
    - cuda-cupti-dev
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - cuda-version ={{ cuda_version }}
    {% endif %}
  host:
    - openssl

  run:
    - legate ={{ legate_version }}

extra:
  recipe-maintainers:
    - m3vaz
