---
{% set name = "legate-profiler" %}

{% if gpu_enabled == "true" %}
  {% set gpu_enabled_bool = true %}
  {% set cpu_gpu_tag='' %}
{% elif gpu_enabled == "false" %}
  {% set gpu_enabled_bool = false %}
  {% set cpu_gpu_tag='_cpu' %}
{% else %}
  {% set gpu_enabled_bool = false %}
{% endif %}

{% set default_env_var = '' %}
{% set legate_version = '' %}
{% if LEGATE_GIT_DESCRIBE_TAG is defined %}
    {% if 'dev' in environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var) %}
        {% set legate_version = (environ.get('LEGATE_GIT_DESCRIBE_TAG') ~ environ.get('LEGATE_GIT_DESCRIBE_NUMBER', default_env_var)).lstrip('v') %}
    {% else %}
        {% set legate_version = environ.get('LEGATE_GIT_DESCRIBE_TAG', default_env_var).lstrip('v') %}
    {% endif %}
{% else %}
    {% set legate_version = '25.08.00' %}
{% endif %}

{% set major_version = (legate_version|string).split(".")[0] %}
{% set minor_version = (legate_version|string).split(".")[1] %}
{% set patch_version = (legate_version|string).split(".")[2] %}

{% set git_rev = environ.get('LEGION_GIT_REV', 'master') %}
{% set git_url = environ.get('LEGION_GIT_URL', 'https://gitlab.com/StanfordLegion/legion.git') %}
{% set git_shallow = environ.get('LEGION_GIT_SHALLOW', true) %}
{% set git_describe_hash = environ.get('LEGATE_GIT_DESCRIBE_HASH', '0') %}

{% set cuda_version='.'.join(environ.get('CUDA', '12.2.2').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0]|int %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: {{ name|lower }}
  version: {{ legate_version }}

source:
  git_url: {{ git_url }}
  git_rev: {{ git_rev }}
  git_shallow: {{ git_shallow }}

build:
  include_recipe: false
  number: 0
  skip: true  # [not linux]
  string: {{ git_describe_hash }}{{ cpu_gpu_tag }}
  script_env:
    - LIBCLANG_PATH=$BUILD_PREFIX/lib
  {% if gpu_enabled_bool %}
    - BUILD_WITH_CUDA=1
  {% else %}
    - BUILD_WITH_CUDA=0
  {% endif %}

requirements:
  build:
    - cmake
    - make
    - rust >={{ rust_min_version }}
    - {{ compiler('c') }}
    - libclang
    - clang
    {% if gpu_enabled_bool %}
    - cuda-nvcc
    - cuda-cudart-dev
    - cuda-cupti-dev
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - cuda-cupti-dev
    - cuda-version ={{ cuda_version }}
    {% endif %}
  host:
    - openssl

  run:
    - legate ={{ legate_version }}

extra:
  recipe-maintainers:
    - m3vaz
