name: Build and test CPU legate.core on GH

concurrency:
  group: ci-cpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

jobs:
  filter-by-triggering-event:
    name: Filter by triggering event
    uses: ./.github/workflows/filter-by-triggering-event.yml

  build-cpu:
    needs: filter-by-triggering-event
    if: needs.filter-by-triggering-event.outputs.ok == 'true'
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: cpu
      # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
      runs-on: ${{ github.repository == 'nv-legate/legate.core' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}

  test-cpu:
    needs:
      - build-cpu
    uses:
      ./.github/workflows/gh-test.yml
    with:
      build-target: cpu
      runs-on: ${{ github.repository == 'nv-legate/legate.core' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}
      test-scope: unit
