name: Build conda nightly release packages

concurrency:
  group: ci-nightly-release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    workflow_dispatch:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

env:
  CHANNEL_TOKEN: "${{ secrets.NV_LEGATE_NIGHTLY_CHANNEL_ACCESS }}"
  ARTIFACTS_DIR: "${{ github.workspace }}/.artifacts"
  ARTIFACT_NAME: "${{ github.event.repository.name }}-gpu-${{ github.sha }}"

jobs:
  build:
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: gpu
      repos-name: ${{ github.event.repository.name }}
      runs-on: ${{ github.repository_owner == 'nv-legate' && 'linux-amd64-cpu16' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}
      build-type: nightly-release
      use-container: true
      ucx-config: no_ucx
      ucx-string: ''

  post-in-container:
    needs:
      - build
    runs-on: ${{ github.repository_owner == 'nv-legate' && 'linux-amd64-cpu16' || 'ubuntu-latest' }}

    container:
      options: -u root
      image: condaforge/miniforge3:latest
    
    steps:
        - name: Post Nightly-release
          run: |
            conda install -c anaconda anaconda-client
            anaconda -V
            anaconda -t $CHANNEL_TOKEN upload --skip-existing -u legate-nightly ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_NAME }}
