name: Build and test GPU legate.core on GH

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

jobs:
  build-gpu:
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: gpu
      # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
      runs-on: ${{ github.repository == 'nv-legate/legate.core' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}

  test-gpu:
    needs:
      - build-gpu
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: Pytest Unit Tests, test-scope: unit, runner: linux-amd64-gpu-v100-latest-1 }
          - { name: Pytest Unit Tests, test-scope: unit, runner: linux-amd64-2gpu }
          - { name: mypy, test-scope: mypy, runner: 'linux-amd64-gpu-v100-latest-1' }
    name: ${{ matrix.name }}
    uses:
      ./.github/workflows/gh-test.yml
    with:
      build-target: gpu
      runs-on: ${{ matrix.runner }}
      sha: ${{ github.sha }}
      test-scope: ${{ matrix.test-scope }}

  cleanup:
    needs:
      - build-gpu
      - test-gpu
    # This ensures the cleanup job runs even if previous jobs fail or the workflow is cancelled.
    if: always()
    uses:
      ./.github/workflows/gh-cleanup.yml
    with:
      build-target: gpu
      sha: ${{ github.sha }}
