# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
name: Build MPI Wrapper Package

on:
  workflow_call:

jobs:
  build:
    name: Build MPI wrapper
    uses: ./.github/workflows/gh-wrapper-packages.yml
    with:
      wrapper-set: mpi
