name: Test legate.core on GH

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      sha:
        required: true
        type: string
      test-scope:
        required: true
        type: string

jobs:
  test:
    if: github.repository_owner == 'nv-legate'
    name: test-${{ inputs.build-target }}-sub-workflow
    runs-on: ${{ inputs.runs-on }}
    container:
      options: -u root
      image: ghcr.io/nv-legate/legate.core-${{ inputs.build-target }}:${{ inputs.sha }}
      env:
        PYTHONDONTWRITEBYTECODE: 1
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    steps:
      - if: inputs.build-target == 'gpu'
        name: Run nvidia-smi to make sure GPU is working
        run: nvidia-smi

      - name: Run legate.core test / analysis
        shell: su coder {0}
        run: run-test-or-analysis ${{ inputs.test-scope }}
