# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
name: Pull Request Labels

concurrency:
  group: label-check-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  merge_group:
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            category:new-feature
            category:improvement
            category:bug-fix
            category:housekeeping
            category:documentation,
            Bug
            Build
            CI
            Docs
            Feature
            Maintenance
