# SPDX-FileCopyrightText: Copyright (c) 2025-2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      cuda_ver:
        type: string
        default: "12.9.0"
      linux_ver:
        type: string
        default: "rockylinux8"
      script:
        type: string
        default: "continuous_integration/scripts/test_source_linux.bash"
      matrix_filter:
        type: string
        default: "."

defaults:
  run:
    shell: bash -eou pipefail {0}

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  compute-matrix:
    runs-on: linux-amd64-cpu4
    timeout-minutes: 15
    outputs:
      MATRIX: ${{ steps.compute-matrix.outputs.MATRIX }}
    steps:
      - name: Compute Build Matrix
        id: compute-matrix
        run: |
          set -eo pipefail

          # please keep the matrices sorted in ascending order by the following:
          #
          #     [ARCH, GCC_VER, BUILD_MODE, GPU]
          #
          export MATRIX="
          # amd64
          - { ARCH: 'amd64', GCC_VER: '10', BUILD_MODE: 'release', GPU: 'l4' }
          - { ARCH: 'amd64', GCC_VER: '14', BUILD_MODE: 'release', GPU: 'l4' }
          "

          MATRIX="$(
            yq -n -o json 'env(MATRIX)' | \
            jq -c '${{ inputs.matrix_filter }} | if (. | length) > 0 then {include: .} else "Error: Empty matrix\n" | halt_error(1) end'
          )"

          echo "MATRIX=${MATRIX}" | tee --append "${GITHUB_OUTPUT}"
  test:
    name: ${{ matrix.ARCH }}, gcc${{ matrix.GCC_VER }}, ${{ matrix.BUILD_MODE }}, ${{ matrix.GPU }}
    needs: compute-matrix
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    runs-on: "linux-${{ matrix.ARCH }}-gpu-${{ matrix.GPU }}-latest-1"
    container:
      image: nvidia/cuda:${{ inputs.cuda_ver }}-base-${{ inputs.linux_ver }}
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add default paths to the env
        run: |
          # The || true is to satisfy the linting check, seems less readable to me.
          echo "$(pwd)/continuous_integration/scripts/tools" >> "${GITHUB_PATH}" || true

      - name: Run nvidia-smi to make sure GPU is working
        run: nvidia-smi

      - name: Setup proxy cache
        uses: nv-gha-runners/setup-proxy-cache@main
        continue-on-error: true

      - name: Download source build from the build job
        uses: actions/download-artifact@v4
        env:
          BUILD_NAME: ${{ matrix.ARCH }}-cuda12-gcc${{ matrix.GCC_VER }}
        with:
          name: source-build-${{ env.BUILD_NAME }}
          path: artifacts

      - name: Run C++ unit tests
        run: ${{ inputs.script }}
