name: Test
on: [push, pull_request]
env:
  DOCKER_AUTH_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
  COMMIT: ${{ github.sha }}
  PROJECT: github-core-ci
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run CI
        run: |
          env
